// Generated by gencpp from file ardrone_project/ImageCalc.msg
// DO NOT EDIT!


#ifndef ARDRONE_PROJECT_MESSAGE_IMAGECALC_H
#define ARDRONE_PROJECT_MESSAGE_IMAGECALC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardrone_project
{
template <class ContainerAllocator>
struct ImageCalc_
{
  typedef ImageCalc_<ContainerAllocator> Type;

  ImageCalc_()
    : time_stamp()
    , is_visible(false)
    , shift(0.0)
    , angle(0.0)
    , distance(0.0)
    , arrow_x(0)
    , arrow_y(0)  {
    }
  ImageCalc_(const ContainerAllocator& _alloc)
    : time_stamp()
    , is_visible(false)
    , shift(0.0)
    , angle(0.0)
    , distance(0.0)
    , arrow_x(0)
    , arrow_y(0)  {
  (void)_alloc;
    }



   typedef ros::Time _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef uint8_t _is_visible_type;
  _is_visible_type is_visible;

   typedef float _shift_type;
  _shift_type shift;

   typedef float _angle_type;
  _angle_type angle;

   typedef float _distance_type;
  _distance_type distance;

   typedef int32_t _arrow_x_type;
  _arrow_x_type arrow_x;

   typedef int32_t _arrow_y_type;
  _arrow_y_type arrow_y;




  typedef boost::shared_ptr< ::ardrone_project::ImageCalc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_project::ImageCalc_<ContainerAllocator> const> ConstPtr;

}; // struct ImageCalc_

typedef ::ardrone_project::ImageCalc_<std::allocator<void> > ImageCalc;

typedef boost::shared_ptr< ::ardrone_project::ImageCalc > ImageCalcPtr;
typedef boost::shared_ptr< ::ardrone_project::ImageCalc const> ImageCalcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_project::ImageCalc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_project::ImageCalc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardrone_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ardrone_project': ['/home/oshri/ros_tutorials/catkin_ws/src/ardrone_project/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_project::ImageCalc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_project::ImageCalc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_project::ImageCalc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_project::ImageCalc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_project::ImageCalc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_project::ImageCalc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_project::ImageCalc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3afd21e3cae9a39680ff48a9777413f3";
  }

  static const char* value(const ::ardrone_project::ImageCalc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3afd21e3cae9a396ULL;
  static const uint64_t static_value2 = 0x80ff48a9777413f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_project::ImageCalc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_project/ImageCalc";
  }

  static const char* value(const ::ardrone_project::ImageCalc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_project::ImageCalc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time time_stamp\n\
bool is_visible\n\
float32 shift\n\
float32 angle\n\
float32 distance\n\
int32 arrow_x\n\
int32 arrow_y\n\
\n\
";
  }

  static const char* value(const ::ardrone_project::ImageCalc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_project::ImageCalc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_stamp);
      stream.next(m.is_visible);
      stream.next(m.shift);
      stream.next(m.angle);
      stream.next(m.distance);
      stream.next(m.arrow_x);
      stream.next(m.arrow_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageCalc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_project::ImageCalc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_project::ImageCalc_<ContainerAllocator>& v)
  {
    s << indent << "time_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "is_visible: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_visible);
    s << indent << "shift: ";
    Printer<float>::stream(s, indent + "  ", v.shift);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "arrow_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arrow_x);
    s << indent << "arrow_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arrow_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_PROJECT_MESSAGE_IMAGECALC_H
