// Generated by gencpp from file keyboard_controller/ImageCalc.msg
// DO NOT EDIT!


#ifndef KEYBOARD_CONTROLLER_MESSAGE_IMAGECALC_H
#define KEYBOARD_CONTROLLER_MESSAGE_IMAGECALC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace keyboard_controller
{
template <class ContainerAllocator>
struct ImageCalc_
{
  typedef ImageCalc_<ContainerAllocator> Type;

  ImageCalc_()
    : shift(0.0)
    , angle(0.0)  {
    }
  ImageCalc_(const ContainerAllocator& _alloc)
    : shift(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _shift_type;
  _shift_type shift;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::keyboard_controller::ImageCalc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::keyboard_controller::ImageCalc_<ContainerAllocator> const> ConstPtr;

}; // struct ImageCalc_

typedef ::keyboard_controller::ImageCalc_<std::allocator<void> > ImageCalc;

typedef boost::shared_ptr< ::keyboard_controller::ImageCalc > ImageCalcPtr;
typedef boost::shared_ptr< ::keyboard_controller::ImageCalc const> ImageCalcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::keyboard_controller::ImageCalc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::keyboard_controller::ImageCalc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace keyboard_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'keyboard_controller': ['/home/oshri/ros_tutorials/catkin_ws/src/ardrone_project/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::keyboard_controller::ImageCalc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keyboard_controller::ImageCalc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keyboard_controller::ImageCalc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3746b94126572c0f0c57557a78bc178d";
  }

  static const char* value(const ::keyboard_controller::ImageCalc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3746b94126572c0fULL;
  static const uint64_t static_value2 = 0x0c57557a78bc178dULL;
};

template<class ContainerAllocator>
struct DataType< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "keyboard_controller/ImageCalc";
  }

  static const char* value(const ::keyboard_controller::ImageCalc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 shift\n\
float32 angle\n\
";
  }

  static const char* value(const ::keyboard_controller::ImageCalc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shift);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageCalc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::keyboard_controller::ImageCalc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::keyboard_controller::ImageCalc_<ContainerAllocator>& v)
  {
    s << indent << "shift: ";
    Printer<float>::stream(s, indent + "  ", v.shift);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEYBOARD_CONTROLLER_MESSAGE_IMAGECALC_H
